### ISSUE TITLE
你好 请问 怎么编译？

### ISSUE THREAD

**Issue by longriyao** [ufoym/Caffe-mini#1]
你好！ 请问一下 怎么编译？

**Comment by ghost** [comment]
hello how to compile the project?

**Comment by ufoym** [comment]
Sorry for late reply.
This repo has been deprecated and will no longer be supported.

To compile the code, you can fire up your Visual Studio and add all source files to an existing project.
For more details, see https://github.com/nViso/Caffe-mini

You can also write a Makefile. Before that, maybe you should replace platform-specific functions like _open, _close, fopen_s.
